-- ==============================================================================
-- CALWAY SUPABASE SEED DATA (26 Kolkata Mandi Products & Categories)
-- Run this script in Supabase SQL Editor after running schema.sql
-- ==============================================================================

-- 1. SEED CATEGORIES
INSERT INTO public.categories (id, name, slug, icon_url, display_order)
VALUES
  ('leafy-greens', 'Leafy Greens (Shaak)', 'leafy-greens', '🥬', 1),
  ('daily-essentials', 'Daily Essentials', 'daily-essentials', '🥔', 2),
  ('kolkata-specials', 'Kolkata Mandi Specials', 'kolkata-specials', '🌶️', 3),
  ('root-vegetables', 'Root Vegetables', 'root-vegetables', '🥕', 4),
  ('exotics-salads', 'Exotic & Salad Greens', 'exotics-salads', '🥦', 5),
  ('combos-kits', 'Mandi Combos & Kits', 'combos-kits', '🧺', 6)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, icon_url = EXCLUDED.icon_url, display_order = EXCLUDED.display_order;

-- 2. SEED PRODUCTS
INSERT INTO public.products (
  id, category_id, name, slug, bengali_name, description,
  price, discounted_price, unit, image_url, is_available, is_featured,
  stock_quantity, mandi_source, arrival_status, rating, reviews_count
)
VALUES
  ('prod-palak', 'leafy-greens', 'Fresh Palak Shaak (Spinach)', 'palak', 'টাটকা পালং শাক', 'Crisp, dewy spinach harvested at dawn from South 24 Parganas farms and brought straight to Koley Mandi. Zero cold storage, no chemical sprays, washed with ozone water.', 28, 40, '250g bunch', 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Koley Mandi, Sealdah', 'Picked 3:45 AM today', 4.9, 184),
  ('prod-lal-shaak', 'leafy-greens', 'Kolkata Lal Shaak (Red Amaranth)', 'lal-shaak', 'দেশি লাল শাক', 'Deep crimson tender red amaranth leaves. A traditional Bengali staple, packed with natural antioxidants and dietary fiber. Cooked with garlic and bori (sun-dried lentil dumplings).', 24, 35, '250g bunch', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Mechua Mandi, Burrabazar', 'Picked 4:10 AM today', 4.8, 129),
  ('prod-pui-shaak', 'leafy-greens', 'Fresh Pui Shaak (Malabar Spinach)', 'pui-shaak', 'টাটকা পুঁই শাক', 'Thick succulent stems and tender green leaves, perfect for authentic Bengali Pui Chingri or Pui Shaak Chorchori with pumpkin and potato chunks.', 32, 45, '500g bundle', 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Koley Mandi, Sealdah', 'Picked 4:00 AM today', 4.7, 92),
  ('prod-methi', 'leafy-greens', 'Fresh Methi Leaves (Fenugreek)', 'methi', 'তাজা মেথি শাক', 'Small, tender aromatic leaves with mild pleasant bitterness. Hand-picked at dawn, free of yellow leaves and roots trimmed cleanly.', 22, 30, '200g bunch', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Posta Wholesale Market', 'Picked 3:50 AM today', 4.9, 114),
  ('prod-coriander', 'leafy-greens', 'Desi Dhone Pata (Fresh Coriander)', 'coriander', 'দেশি সুগন্ধি ধনে পাতা', 'Intensely fragrant desi coriander with small leaves and thin tender stems. The real Kolkata aroma for your morning dal and fish curries.', 18, 25, '150g bunch', 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Koley Mandi, Sealdah', 'Picked 4:20 AM today', 4.9, 310),
  ('prod-kacha-lanka', 'kolkata-specials', 'Fresh Kolkata Kacha Lanka (Green Chili)', 'kacha-lanka', 'তাজা কাঁচা লঙ্কা', 'Fiery, snappy and fresh green chillies directly from Diamond Harbour farms via Mechua Mandi. Snaps cleanly with an explosive spicy aroma.', 20, 30, '200g pack', 'https://images.unsplash.com/photo-1525607551316-4a8e16d1f9ba?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Mechua Mandi, Burrabazar', 'Picked 4:30 AM today', 4.9, 420),
  ('prod-jyoti-potato', 'daily-essentials', 'Budge Budge Jyoti Potatoes', 'jyoti-potato', 'নতুন জ্যোতি আলু', 'Thin-skinned, smooth textured Jyoti potatoes sourced directly from Hooghly district farmlands. Wipes clean, cooks evenly, and absorbs rich gravies perfectly.', 34, 45, '1 kg', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Koley Mandi, Sealdah', 'Arrived 3:30 AM today', 4.8, 540),
  ('prod-chandramukhi-potato', 'daily-essentials', 'Hooghly Chandramukhi Potatoes', 'chandramukhi-potato', 'আসল চন্দ্রমুখী আলু', 'The gold standard for Kolkata food lovers. Chandler-smooth, melts into velvet when boiled, perfect for Aloo Posto and Biryani. Hand-sorted at dawn.', 42, 55, '1 kg', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Koley Mandi, Sealdah', 'Arrived 3:45 AM today', 4.9, 380),
  ('prod-desi-tomato', 'daily-essentials', 'Fresh Desi Country Tomatoes', 'desi-tomato', 'দেশি পাকা টমেটো', 'Tangy, juicy country-style tomatoes. Distinct sour balance that commercial hybrid varieties lack. Makes aromatic sweet-tangy Kolkata Khejur-Amsotto Chutney.', 38, 52, '1 kg', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Mechua Mandi, Burrabazar', 'Picked 4:15 AM today', 4.8, 260),
  ('prod-red-onion', 'daily-essentials', 'Nasik Pink Mandi Onions', 'red-onion', 'তাজা গোলাপি পেঁয়াজ', 'Crisp medium-sized pink onions with paper-dry skin and tight layers. Pungent sweetness without excessive water weight.', 45, 60, '1 kg', 'https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Posta Wholesale Market', 'Arrived 4:00 AM today', 4.7, 490),
  ('prod-ginger', 'daily-essentials', 'Fresh Pahadi Ginger (Ada)', 'ginger', 'টাটকা আদা', 'Juicy, fibrous ginger roots sourced from North Bengal hill tracts. Pungent, spicy kick that enlivens morning tea and gravies.', 48, 65, '250g', 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Posta Wholesale Market', 'Arrived 4:20 AM today', 4.9, 210),
  ('prod-garlic', 'daily-essentials', 'Desi Small-Clove Garlic (Roshun)', 'garlic', 'দেশি রসুন', 'Tight, firm bulbs of desi garlic with natural purple streaks. Super aromatic cloves with intense flavor so you need fewer pods.', 65, 85, '250g', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Posta Wholesale Market', 'Arrived 3:45 AM today', 4.8, 175),
  ('prod-potol', 'kolkata-specials', 'Fresh Tender Potol (Pointed Gourd)', 'potol', 'টাটকা কচি পটল', 'Small, tender, seedless green pointed gourds from Nadia district. Scrapes cleanly without tough skin, ideal for Potoler Dolma or mustard gravy.', 36, 50, '500g', 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Koley Mandi, Sealdah', 'Picked 4:25 AM today', 4.9, 195),
  ('prod-jhinge', 'kolkata-specials', 'Crisp Tender Jhinge (Ridge Gourd)', 'jhinge', 'টাটকা কচি ঝিঙে', 'Slender, dark green ridge gourds with crunchy ridged skin and sweet watery pulp. Unrivaled for classic Jhinge Aloo Posto.', 32, 45, '500g', 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Mechua Mandi, Burrabazar', 'Picked 4:10 AM today', 4.8, 160),
  ('prod-begun', 'kolkata-specials', 'Muktakeshi Begun (Purple Eggplant)', 'begun', 'নরম মুক্তকেশী বেগুন', 'Glossy deep violet eggplant with almost zero seeds and tender white flesh. Perfect for Bengali Begun Bhaja with rice and dal or smoked Begun Pora.', 38, 50, '500g (approx 2 pcs)', 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Koley Mandi, Sealdah', 'Picked 4:00 AM today', 4.9, 240),
  ('prod-raw-banana', 'kolkata-specials', 'Fresh Kacha Kola (Raw Green Banana)', 'raw-banana', 'টাটকা কাঁচকলা', 'Starchy green plantains straight from South Bengal orchards. Traditional remedy for upset stomachs and the secret base for hearty Kofta curry.', 25, 35, '4 pcs pack', 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Mechua Mandi, Burrabazar', 'Picked 4:35 AM today', 4.7, 88),
  ('prod-carrot', 'root-vegetables', 'Crunchy Desi Gajor (Carrots)', 'carrot', 'টাটকা লাল গাজর', 'Sweet, vibrant red carrots with crisp snap and natural sweetness. Freshly washed of field soil at the mandi sorting hub.', 32, 45, '500g', 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Posta Wholesale Market', 'Arrived 3:55 AM today', 4.8, 180),
  ('prod-beetroot', 'root-vegetables', 'Ruby Red Mandi Beetroot (Bit)', 'beetroot', 'রঙিন তাজা বিট', 'Firm, earthy globes of crimson beetroots with thin skin. Unmatched for daily morning detox juices, Kolkata-style vegetable chops, and salads.', 28, 40, '500g', 'https://images.unsplash.com/photo-1561047029-3000c68339ca?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Posta Wholesale Market', 'Arrived 4:05 AM today', 4.9, 140),
  ('prod-mula', 'root-vegetables', 'White Desi Radish (Mula)', 'mula', 'মিষ্টি দেশি মূলো', 'Crisp white radishes with fresh dewy greens attached. Mildly peppery without bitter bite, superb for morning parathas and Mulo Saag.', 22, 30, '500g bunch', 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Koley Mandi, Sealdah', 'Picked 4:10 AM today', 4.7, 95),
  ('prod-sweet-potato', 'root-vegetables', 'Ranga Aloo (Sweet Potatoes)', 'sweet-potato', 'মিষ্টি রাঙা আলু', 'Rose-skinned sweet potatoes with sweet golden interior. A favourite addition to Bengali Shukto and roasted winter snacks.', 36, 50, '500g', 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Koley Mandi, Sealdah', 'Arrived 3:50 AM today', 4.8, 110),
  ('prod-cucumber', 'exotics-salads', 'Crisp English Seedless Cucumber', 'cucumber', 'ক্রিস্পি শসা', 'Thin-skinned, seedless, ultra-crisp cucumbers. Refreshing water crunch with zero bitter ends. Ready for morning salads and raita.', 35, 48, '500g (approx 2 pcs)', 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Mechua Mandi, Burrabazar', 'Arrived 4:15 AM today', 4.8, 230),
  ('prod-broccoli', 'exotics-salads', 'Fresh Green Broccoli Florets', 'broccoli', 'টাটকা ব্রকলি', 'Dense, tight dark emerald crowns of fresh broccoli. High glucoraphanin content, harvested chilled and delivered to prevent yellowing.', 55, 80, '1 head (approx 400g)', 'https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Posta Wholesale Exotic Hub', 'Arrived 4:20 AM today', 4.9, 165),
  ('prod-mushroom', 'exotics-salads', 'Fresh White Button Mushrooms', 'mushroom', 'তাজা বাটন মাশরুম', 'Snow-white plump button mushrooms packed in breathable punnets. Firm caps and clean stems, perfect for stir-fries, soups, and curries.', 45, 60, '200g punnet', 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Posta Wholesale Exotic Hub', 'Arrived 4:30 AM today', 4.8, 190),
  ('prod-shukto-kit', 'combos-kits', 'Authentic Kolkata Shukto Veggie Kit', 'shukto-kit', 'খাস কলকাতার শুক্তো কিট', 'All essential fresh veggies for the traditional Bengali bitter-sweet starter course: Bitter Gourd (Ucche), Green Plantain (Kanchakola), Sweet Potato (Ranga Aloo), Drumstick (Sojne Danta), and Raw Papaya (Pepe) in exact culinary ratios!', 89, 125, '850g pre-portioned kit', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Hand-curated at Koley Mandi', 'Curated 4:45 AM today', 5, 310),
  ('prod-daily-curry-kit', 'combos-kits', 'Morning Daily Essentials Basket Kit', 'daily-curry-kit', 'দৈনিক রান্নার কম্বো প্যাক', 'Every household''s daily backbone: 1kg Jyoti Potatoes + 1kg Pink Onions + 500g Desi Tomatoes + 200g Green Chilies + 100g Desi Coriander + 100g Fresh Ginger. Everything you need for the day''s meals!', 149, 210, '3.5 kg total combo', 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=600&q=80', true, true, 100, 'Direct Wholesale Assortment', 'Curated 4:30 AM today', 4.9, 425),
  ('prod-green-salad-kit', 'combos-kits', 'Dewy Morning Detox Salad Kit', 'green-salad-kit', 'ডিটক্স সালাড কিট', 'Crisp morning salad set: 2 English Cucumbers + 250g Red Carrots + 250g Sweet Beetroots + 100g Green Capsicum + 2 fresh juicy Kagji lemons. Ready to slice for morning fitness breakfast!', 79, 110, '700g salad combo', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80', true, false, 100, 'Dawn Garden Sourcing', 'Curated 4:40 AM today', 4.9, 185)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, price = EXCLUDED.price, discounted_price = EXCLUDED.discounted_price, image_url = EXCLUDED.image_url, stock_quantity = EXCLUDED.stock_quantity;
